name: Deploy

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # checkout v2, with recursive submodule update
      - name: Checkout 🛎️
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      # Build everything (in docker)
      - name: Build 🔨
        run: ./test.sh

      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
