name: PR Tests

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # checkout v2, with recursive submodule update
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Build everything (in docker)
      - name: Build 🔨
        run: ./test.sh
